# Custom Language File for Launcher Customizer

[ejs.app]
title = "ChromaLife Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/noappertBD/ChromaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/gD5yt8k4NY"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"
